### ISSUE TITLE
Make core.rtcpeerconnection / core.rtcdatachannel exist

### ISSUE THREAD

**Issue by willscott** [freedomjs/freedom-for-node#2]
likely via http://js-platform.github.io/node-webrtc/

**Comment by soycode** [comment]
Taking this as a renewed priority for getting uProxy-for-cloud running in node rather than Docker images with Firefox (thus hopefully improving setup time, performance, etc. etc.).

**Comment by soycode** [comment]
Some notes - node-wrtc has some build issues on OSX, https://github.com/js-platform/node-webrtc/issues/235#issuecomment-152447773

May still go with it, but I'm also looking into other fill options. One that I'm not sure if it's appropriate, but may be convenient if so - https://github.com/mappum/electron-webrtc

**Comment by soycode** [comment]
It exists now (w/caveat that building requires Linux rather than OSX) - https://github.com/freedomjs/freedom-for-node/pull/40
